[package]
name = "include-zstd-macro"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0" }
zstd = { version = "0.13" }
proc-macro-crate = { version = "3.2" }
